# Generated by Django 5.0.6 on 2024-07-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_category_categoryname_alter_listing_imageurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(max_length=260),
        ),
    ]
