# Generated by Django 5.0.6 on 2024-07-14 22:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_rename_bid_amount_bid_bidamount_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='createdAt',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
