# Generated by Django 5.0.6 on 2024-07-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_listing_description_alter_listing_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(max_length=360),
        ),
        migrations.AlterField(
            model_name='listing',
            name='imageUrl',
            field=models.CharField(max_length=360),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
